networks:
  web:
    external: true
  ghassen-io-network:
    driver: bridge

services:
  orbit-ways-be:
    image: ghassenbrg/orbit-ways-be:1.0.0-SNAPSHOT
    volumes:
      - ./config/orbit-ways-be:/config:ro   # Spring Boot reads /config/application.properties
    restart: unless-stopped
    networks:
      - ghassen-io-network

  ghassen-io-fe:
    image: ghassenbrg/ghassen-io-fe:1.0.0-SNAPSHOT
    # Mount ONE global nginx.conf (the image expects this path)
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If the image DOESN'T already contain built files, uncomment this to prove content is served:
      # - ./site:/usr/share/nginx/html:ro
    depends_on:
      - orbit-ways-be
    restart: unless-stopped
    networks:
      - ghassen-io-network    # for proxy_pass to orbit-ways-be
      - web                   # so Traefik can reach the FE
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # Traefik v3 syntax: OR between hosts
      - "traefik.http.routers.ghassen-io.rule=(Host(`ghassen.io`) || Host(`www.ghassen.io`))"
      - "traefik.http.routers.ghassen-io.entrypoints=websecure"
      - "traefik.http.routers.ghassen-io.tls.certresolver=le"
      - "traefik.http.services.ghassen-io.loadbalancer.server.port=80"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.ghassen-io-redirect.rule=(Host(`ghassen.io`) || Host(`www.ghassen.io`))"
      - "traefik.http.routers.ghassen-io-redirect.entrypoints=web"
      - "traefik.http.routers.ghassen-io-redirect.middlewares=to-https"
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
