networks:
  # External network created by your Traefik stack (from traefik-compose.yml)
  web:
    external: true

  # Internal network for FE <-> BE
  ghassen-io-network:
    driver: bridge

services:
  orbit-ways-be:
    image: ghassenbrg/orbit-ways-be:1.0.0-SNAPSHOT
    # Mount a directory (Spring Boot will auto-read /config/application.properties)
    volumes:
      - ./config/orbit-ways-be:/config:ro
    restart: unless-stopped
    networks:
      - ghassen-io-network

  ghassen-io-fe:
    image: ghassenbrg/ghassen-io-fe:1.0.0-SNAPSHOT
    # No host ports: Traefik terminates HTTPS and forwards to container:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If your static files are NOT baked into the image, uncomment the next line:
      # - ./site:/usr/share/nginx/html:ro
    depends_on:
      - orbit-ways-be
    restart: unless-stopped
    networks:
      - ghassen-io-network
      - web
    labels:
      - "traefik.enable=true"

      # HTTPS router for ghassen.io + www (Traefik on 443)
      - "traefik.http.routers.ghassen-io.rule=Host(`ghassen.io`,`www.ghassen.io`)"
      - "traefik.http.routers.ghassen-io.entrypoints=websecure"
      - "traefik.http.routers.ghassen-io.tls.certresolver=le"
      # Tell Traefik to talk to port 80 inside the container (Nginx)
      - "traefik.http.services.ghassen-io.loadbalancer.server.port=80"

      # HTTP -> HTTPS redirect (Traefik on 80)
      - "traefik.http.routers.ghassen-io-redirect.rule=Host(`ghassen.io`,`www.ghassen.io`)"
      - "traefik.http.routers.ghassen-io-redirect.entrypoints=web"
      - "traefik.http.routers.ghassen-io-redirect.middlewares=to-https"
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
